project_id = "jdjrdshcacrfskqzluxi"

[functions.scan-receipt]
verify_jwt = true

[functions.geocode]
verify_jwt = true

[functions.reverse-geocode]
verify_jwt = false

[functions.smart-address]
verify_jwt = false

[functions.adjust-km]
verify_jwt = true

[functions.nearby-places]
verify_jwt = false
