// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.2";

// src/lib/mcp/tools/list-trips.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-trips.ts
var list_trips_default = defineTool({
  name: "list_trips",
  title: "List trips",
  description: "List the signed-in driver's logged trips, optionally filtered by date range and category (business, personal, uncategorized).",
  inputSchema: {
    start_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Earliest trip date, YYYY-MM-DD."),
    end_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Latest trip date, YYYY-MM-DD."),
    category: z.enum(["business", "personal", "uncategorized"]).optional().describe("Filter by trip category."),
    limit: z.number().int().min(1).max(200).optional().describe("Maximum trips to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("trips").select("id, date, start_time, end_time, start_location, end_location, kilometres, category, company, notes").order("date", { ascending: false }).order("start_time", { ascending: false }).limit(limit ?? 50);
    if (start_date) query = query.gte("date", start_date);
    if (end_date) query = query.lte("date", end_date);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const trips = (data ?? []).map((t) => ({
      id: t.id,
      date: t.date,
      start_time: t.start_time,
      end_time: t.end_time,
      start_location: t.start_location,
      end_location: t.end_location,
      kilometres: t.kilometres,
      category: t.category,
      company: t.company ?? null,
      notes: t.notes ?? null
    }));
    const totalKm = trips.reduce((sum, t) => sum + (t.kilometres ?? 0), 0);
    return {
      content: [{ type: "text", text: `${trips.length} trips, ${totalKm.toFixed(1)} km total.` }],
      structuredContent: { trips, total_km: Number(totalKm.toFixed(1)) }
    };
  }
});

// src/lib/mcp/tools/log-trip.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z2 } from "npm:zod@^3.25.76";
var log_trip_default = defineTool2({
  name: "log_trip",
  title: "Log a trip",
  description: "Record a new trip for the signed-in driver with date, times, locations, distance and category.",
  inputSchema: {
    date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Trip date, YYYY-MM-DD (Pacific time)."),
    start_time: z2.string().describe("Start time, HH:MM (24-hour, Pacific time)."),
    end_time: z2.string().describe("End time, HH:MM (24-hour, Pacific time)."),
    start_location: z2.string().trim().min(1).describe("Where the trip started."),
    end_location: z2.string().trim().min(1).describe("Where the trip ended."),
    kilometres: z2.number().positive().describe("Distance driven in kilometres."),
    category: z2.enum(["business", "personal", "uncategorized"]).describe("Trip category."),
    company: z2.string().trim().optional().describe("Platform or company, e.g. Uber, DoorDash, Skip."),
    notes: z2.string().trim().optional().describe("Free-form notes about the trip.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("trips").insert({
      user_id: ctx.getUserId(),
      date: input.date,
      start_time: input.start_time,
      end_time: input.end_time,
      start_location: input.start_location,
      end_location: input.end_location,
      kilometres: input.kilometres,
      category: input.category,
      company: input.company ?? null,
      notes: input.notes ?? null
    }).select("id, date, kilometres, category").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged ${data.kilometres} km ${data.category} trip on ${data.date}.` }],
      structuredContent: { trip: { id: data.id, date: data.date, kilometres: data.kilometres, category: data.category } }
    };
  }
});

// src/lib/mcp/tools/list-expenses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_expenses_default = defineTool3({
  name: "list_expenses",
  title: "List expenses",
  description: "List the signed-in driver's expenses, optionally filtered by date range, category or vendor name.",
  inputSchema: {
    start_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Earliest expense date, YYYY-MM-DD."),
    end_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Latest expense date, YYYY-MM-DD."),
    category: z3.string().trim().optional().describe("Expense category, e.g. fuel, repairs, insurance, grocery."),
    vendor: z3.string().trim().optional().describe("Vendor name (partial match)."),
    limit: z3.number().int().min(1).max(200).optional().describe("Maximum expenses to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, category, vendor, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("expenses").select("id, date, vendor_name, amount, category, purpose, notes").is("deleted_at", null).order("date", { ascending: false }).limit(limit ?? 50);
    if (start_date) query = query.gte("date", start_date);
    if (end_date) query = query.lte("date", end_date);
    if (category) query = query.eq("category", category);
    if (vendor) query = query.ilike("vendor_name", `%${vendor}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const expenses = (data ?? []).map((e) => ({
      id: e.id,
      date: e.date,
      vendor_name: e.vendor_name,
      amount: e.amount,
      category: e.category,
      purpose: e.purpose,
      notes: e.notes ?? null
    }));
    const total = expenses.reduce((sum, e) => sum + (e.amount ?? 0), 0);
    return {
      content: [{ type: "text", text: `${expenses.length} expenses totalling $${total.toFixed(2)}.` }],
      structuredContent: { expenses, total_amount: Number(total.toFixed(2)) }
    };
  }
});

// src/lib/mcp/tools/log-expense.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z4 } from "npm:zod@^3.25.76";
var log_expense_default = defineTool4({
  name: "log_expense",
  title: "Log an expense",
  description: "Record a new expense for the signed-in driver with date, vendor, amount and category.",
  inputSchema: {
    date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Expense date, YYYY-MM-DD (Pacific time)."),
    vendor_name: z4.string().trim().min(1).describe("Vendor or store name."),
    amount: z4.number().positive().describe("Amount in CAD."),
    category: z4.string().trim().min(1).describe("Category, e.g. fuel, repairs, insurance, licence, interest, grocery, other."),
    purpose: z4.enum(["business", "personal"]).optional().describe("Whether the expense is business or personal (default business)."),
    notes: z4.string().trim().optional().describe("Free-form notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("expenses").insert({
      user_id: ctx.getUserId(),
      date: input.date,
      vendor_name: input.vendor_name,
      amount: input.amount,
      category: input.category,
      purpose: input.purpose ?? "business",
      notes: input.notes ?? null
    }).select("id, date, vendor_name, amount, category, purpose").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged $${data.amount} at ${data.vendor_name} on ${data.date}.` }],
      structuredContent: {
        expense: {
          id: data.id,
          date: data.date,
          vendor_name: data.vendor_name,
          amount: data.amount,
          category: data.category,
          purpose: data.purpose
        }
      }
    };
  }
});

// src/lib/mcp/tools/tax-year-summary.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@3.0.2";
import { z as z5 } from "npm:zod@^3.25.76";
var tax_year_summary_default = defineTool5({
  name: "tax_year_summary",
  title: "Tax year summary",
  description: "Summarize a tax year for the signed-in driver: business vs personal kilometres, odometer total, unlogged gap, business-use percentage, and expense totals by category.",
  inputSchema: {
    year: z5.number().int().min(2e3).max(2100).describe("Tax year, e.g. 2026.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const from = `${year}-01-01`;
    const to = `${year}-12-31`;
    const km = { business: 0, personal: 0, uncategorized: 0 };
    const pageSize = 1e3;
    for (let offset = 0; ; offset += pageSize) {
      const { data, error } = await supabase.from("trips").select("kilometres, category").gte("date", from).lte("date", to).range(offset, offset + pageSize - 1);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      for (const t of data ?? []) {
        const key = t.category === "business" || t.category === "personal" ? t.category : "uncategorized";
        km[key] += t.kilometres ?? 0;
      }
      if (!data || data.length < pageSize) break;
    }
    const byCategory = {};
    let expenseTotal = 0;
    for (let offset = 0; ; offset += pageSize) {
      const { data, error } = await supabase.from("expenses").select("amount, category").is("deleted_at", null).gte("date", from).lte("date", to).range(offset, offset + pageSize - 1);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
      for (const e of data ?? []) {
        byCategory[e.category] = Number(((byCategory[e.category] ?? 0) + (e.amount ?? 0)).toFixed(2));
        expenseTotal += e.amount ?? 0;
      }
      if (!data || data.length < pageSize) break;
    }
    const { data: odo, error: odoError } = await supabase.from("odometer_readings").select("start_reading, end_reading").eq("year", year).maybeSingle();
    if (odoError) return { content: [{ type: "text", text: odoError.message }], isError: true };
    const loggedKm = km.business + km.personal + km.uncategorized;
    const odometerKm = odo?.end_reading != null ? odo.end_reading - odo.start_reading : null;
    const unloggedKm = odometerKm != null ? Math.max(0, Number((odometerKm - loggedKm).toFixed(1))) : null;
    const businessPercentOfLogged = loggedKm > 0 ? Number((km.business / loggedKm * 100).toFixed(1)) : 0;
    const businessPercentOfOdometer = odometerKm && odometerKm > 0 ? Number((km.business / odometerKm * 100).toFixed(1)) : null;
    const summary = {
      year,
      business_km: Number(km.business.toFixed(1)),
      personal_km: Number(km.personal.toFixed(1)),
      uncategorized_km: Number(km.uncategorized.toFixed(1)),
      logged_km: Number(loggedKm.toFixed(1)),
      odometer_km: odometerKm,
      unlogged_km: unloggedKm,
      business_percent_of_logged: businessPercentOfLogged,
      business_percent_of_odometer: businessPercentOfOdometer,
      expense_total: Number(expenseTotal.toFixed(2)),
      expenses_by_category: byCategory
    };
    return {
      content: [
        {
          type: "text",
          text: `${year}: ${summary.business_km} business km of ${summary.logged_km} logged (${businessPercentOfLogged}%), expenses $${summary.expense_total}.`
        }
      ],
      structuredContent: { summary }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jdjrdshcacrfskqzluxi";
var mcp_default = defineMcp({
  name: "drive-deduct",
  title: "Drive & Deduct",
  version: "0.1.0",
  instructions: "Mileage and expense tracking for a Canadian self-employed driver (CRA Form T2125). Use `list_trips` and `log_trip` for kilometres, `list_expenses` and `log_expense` for spending, and `tax_year_summary` for yearly business-use percentage and totals. All dates are Pacific time in YYYY-MM-DD format.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_trips_default, log_trip_default, list_expenses_default, log_expense_default, tax_year_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
